# Generated by Django 6.0 on 2026-05-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_order_orderline_delete_postorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateField(),
        ),
    ]
