# Generated by Django 6.0 on 2026-06-07 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_order_invoice_number_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('qris', 'Qris'), ('transfer', 'Transfer'), ('debit', 'Debit'), ('credit', 'Credit')], default='cash', max_length=200)),
                ('paid_amount', models.FloatField()),
                ('change_amount', models.FloatField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pos.order')),
            ],
        ),
    ]
