# Generated by Django 6.0 on 2026-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_product_stock_stockin_stockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=200),
        ),
    ]
