# Generated by Django 6.0 on 2026-06-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_stockin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.order'),
        ),
    ]
